### ISSUE TITLE
feat: Dependency listing

### ISSUE THREAD

**Issue by brian6932** [rocolatey/rocolatey#226]
Either a `tree` subcommand (like `pactree`) or a flag under `list` would work https://github.com/chocolatey/choco/issues/1276.

**Comment by mwallner** [comment]
Hi @brian6932 , just for clarification: do you want this feature to work on local/installed packages only or also for remote packages on a package repository?

**Comment by brian6932** [comment]
`pactree` works locally, but I guess having both's not bad, but should probably have a flag for searching.

<details>
	<summary>pactree example</summary>

```
# pactree pacman
pacman
├─bash>=4.2.045
├─gettext
│ ├─libintl
│ │ ├─gcc-libs
│ │ └─libiconv
│ │   ├─gcc-libs
│ │   └─libintl
│ ├─libgettextpo
│ │ └─gcc-libs
│ └─libasprintf
│   └─gcc-libs
├─gnupg
│ ├─bzip2
│ │ └─libbz2
│ │   └─gcc-libs
│ ├─libassuan
│ │ ├─gcc-libs
│ │ └─libgpg-error
│ │   ├─bash provides sh
│ │   ├─libiconv
│ │   └─libintl
│ ├─libbz2
│ ├─libcurl
│ │ ├─brotli
│ │ │ └─gcc-libs
│ │ ├─ca-certificates
│ │ │ ├─bash
│ │ │ ├─openssl
│ │ │ │ └─libopenssl
│ │ │ ├─findutils
│ │ │ │ ├─libiconv
│ │ │ │ └─libintl
│ │ │ ├─coreutils
│ │ │ │ ├─gmp
│ │ │ │ ├─libiconv
│ │ │ │ └─libintl
│ │ │ ├─sed
│ │ │ │ ├─libintl
│ │ │ │ └─bash provides sh
│ │ │ └─p11-kit
│ │ │   └─libp11-kit
│ │ │     ├─libffi
│ │ │     ├─libintl
│ │ │     └─libtasn1
│ │ │       └─info
│ │ │         ├─gzip
│ │ │         │ ├─bash
│ │ │         │ └─less
│ │ │         │   ├─ncurses
│ │ │         │   │ └─gcc-libs
│ │ │         │   └─libpcre2_8
│ │ │         │     └─gcc-libs
│ │ │         ├─libxcrypt
│ │ │         ├─libintl
│ │ │         └─ncurses
│ │ ├─heimdal-libs
│ │ │ ├─libdb
│ │ │ │ └─gcc-libs
│ │ │ ├─libxcrypt
│ │ │ ├─libedit
│ │ │ │ ├─ncurses
│ │ │ │ └─bash provides sh
│ │ │ ├─libsqlite
│ │ │ └─libopenssl
│ │ ├─libidn2
│ │ │ ├─libunistring
│ │ │ │ └─libiconv
│ │ │ └─libintl
│ │ ├─libunistring
│ │ ├─libnghttp2
│ │ │ └─gcc-libs
│ │ ├─libpsl
│ │ │ ├─libidn2
│ │ │ └─libunistring
│ │ ├─libssh2
│ │ │ ├─ca-certificates
│ │ │ ├─openssl
│ │ │ └─zlib
│ │ │   └─gcc-libs
│ │ ├─openssl
│ │ ├─zlib
│ │ └─libzstd
│ │   └─gcc-libs
│ ├─libgcrypt
│ │ └─libgpg-error
│ ├─libgpg-error
│ ├─libgnutls
│ │ ├─gcc-libs
│ │ ├─libidn2
│ │ ├─libiconv
│ │ ├─libintl
│ │ ├─gmp
│ │ ├─libnettle
│ │ │ └─libhogweed
│ │ │   └─gmp
│ │ ├─libp11-kit
│ │ ├─libtasn1
│ │ └─zlib
│ ├─libiconv
│ ├─libintl
│ ├─libksba
│ │ ├─gcc-libs
│ │ └─libgpg-error
│ ├─libnpth
│ │ └─gcc-libs
│ ├─libreadline
│ │ └─ncurses
│ ├─libsqlite
│ ├─nettle
│ │ └─libnettle
│ ├─pinentry
│ │ ├─ncurses
│ │ ├─libassuan
│ │ └─libgpg-error
│ └─zlib
├─curl
│ ├─ca-certificates
│ ├─libcurl
│ ├─libunistring
│ ├─libnghttp2
│ ├─libpsl
│ ├─openssl
│ └─zlib
├─pacman-mirrors
├─msys2-keyring
├─which
│ └─bash provides sh
├─bzip2
├─xz
│ ├─liblzma
│ ├─libiconv
│ └─libintl
└─zstd
  ├─gcc-libs
  └─libzstd
```
</details>

**Comment by mwallner** [comment]
should be doable, I think a feature flag in "list" is probably the way to go. (thinking `-deptree` or `-show-deps`)

**Comment by mwallner** [comment]
just realized: "choco list" lists _all_ packages currently installed, therefore a 'pactree'-style implementation would also create the "full tree" of all packages - what is your requirement here? / if you only want to create the tree for a single package, it would make sense to put it in "choco/roco info" (because this command already takes a package id as parameter).

this would probably be nice in combination with #227 (although nesting depth might become an issue)

**Comment by brian6932** [comment]
A full dep tree for `list` sounds interesting, not a requirement of mine though, as pactree can't do that either afaik, would just like to know for specific packages.

**Comment by mwallner** [comment]
Starting with roco 0.9.1, you now can pass `--dependency-tree` to the `roco list` command - either with an additional package filter or without.

Let me know if that's what you imagined, I already like/use the feature myself but since it's not a "choco compatible command" it's likely to change/be tweaked a bit in the future so it better fits it's users needs. (primarily thinking about #227)
